//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentHouseAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int IDBinhLuan { get; set; }
        public Nullable<int> IDNhaTro { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> ThoiGianBL { get; set; }
    }
}
