//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RenthouseAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietNhaTro
    {
        public int MaDuLieu { get; set; }
        public Nullable<int> IDNhaTro { get; set; }
        public string MoTa { get; set; }
        public string TinhTrang { get; set; }
        public string Loai { get; set; }
        public string DienThoai { get; set; }
        public string HinhAnh1 { get; set; }
        public string HinhAnh2 { get; set; }
        public string HinhAnh3 { get; set; }
        public Nullable<float> KinhDo { get; set; }
        public Nullable<float> ViDo { get; set; }
        public string ChuThich { get; set; }
    }
}
