//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentHouseAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class duong
    {
        public int MaDuong { get; set; }
        public string TenDuong { get; set; }
    }
}
