//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentHouseAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public int IDNguoiDung { get; set; }
        public string Username { get; set; }
        public string Ten { get; set; }
        public string Pass { get; set; }
        public Nullable<System.DateTime> NamSinh { get; set; }
        public string Mail { get; set; }
        public string Avatar { get; set; }
        public Nullable<int> SoDienThoai { get; set; }
    }
}
