//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentHouseAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaTro
    {
        public int IDNhaTro { get; set; }
        public Nullable<float> DienTich { get; set; }
        public string SoNha { get; set; }
        public Nullable<int> GiaPhong { get; set; }
        public Nullable<int> MaDuong { get; set; }
        public Nullable<int> MaPhuong { get; set; }
        public Nullable<int> MaQuanHuyen { get; set; }
        public Nullable<int> MaTinhThanh { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> IDNguoiDang { get; set; }
        public string HinhAnh { get; set; }
    }
}
